-- ============================================================================
-- lang_custom.sql - Spanish (Latin American) translations for Patient Express Portal
-- lang_code = 'el' (Spanish Latin American), lang_description = 'Spanish (Latin American)'
-- Self-contained: run this script directly. It populates lang_custom AND
-- synchronizes into lang_languages / lang_constants / lang_definitions.
-- No need for Administration > Language > Add/Manage Translations sync step.
--
-- The project UI source strings are in ENGLISH (xl/xlt/xla). This script
-- provides the SPANISH translations so Spanish-language users see it in
-- Spanish, while English/other users see the English source strings.
--
-- Existing translations are NOT overwritten.
-- ============================================================================

-- Generated from xl()/xlt() calls across the project source

START TRANSACTION;

INSERT INTO lang_custom (lang_description, lang_code, constant_name, definition) VALUES
('Spanish (Latin American)', 'el', 'years', 'años'),
('Spanish (Latin American)', 'el', '-- New In-house Physician or Other... --', '-- Nuevo Médico de la Casa u Otro... --'),
('Spanish (Latin American)', 'el', '-- Select Modality --', '-- Seleccionar Modalidad --'),
('Spanish (Latin American)', 'el', '-- Select Region... --', '-- Seleccionar Región... --'),
('Spanish (Latin American)', 'el', '-- Select Service... --', '-- Seleccionar Servicio... --'),
('Spanish (Latin American)', 'el', '-- No folder selected (automatic will be used) --', '-- Sin carpeta seleccionada (se usará la automática) --'),
('Spanish (Latin American)', 'el', 'Draft', 'Borrador'),
('Spanish (Latin American)', 'el', '⚡ Quick Templates — Normal Report', '⚡ Plantillas Rápidas — Informe Normal'),
('Spanish (Latin American)', 'el', 'Completed', 'Completado'),
('Spanish (Latin American)', 'el', 'Observations and Suggestions', 'Observaciones y Sugerencias'),
('Spanish (Latin American)', 'el', 'PDF Destination Folder', 'Carpeta Destino del PDF'),
('Spanish (Latin American)', 'el', 'Study Data', 'Datos del Estudio'),
('Spanish (Latin American)', 'el', 'Conclusion / Diagnostic Impression', 'Conclusión / Impresión Diagnóstica'),
('Spanish (Latin American)', 'el', 'Technique / Methodology', 'Técnica / Metodología'),
('Spanish (Latin American)', 'el', 'Interpretation / Findings', 'Interpretación / Hallazgos'),
('Spanish (Latin American)', 'el', 'ABNORMAL', 'ANORMAL'),
('Spanish (Latin American)', 'el', 'Access all medical features in the OpenEMR Portal', 'Accede a todas las funcionalidades médicas en el Portal OpenEMR'),
('Spanish (Latin American)', 'el', 'Access my Results', 'Ingresar a mis Resultados'),
('Spanish (Latin American)', 'el', 'Access the Full OpenEMR Portal', 'Acceder al Portal Completo OpenEMR'),
('Spanish (Latin American)', 'el', 'Active Patient in System', 'Paciente Activo en Sistema'),
('Spanish (Latin American)', 'el', 'Age', 'Edad'),
('Spanish (Latin American)', 'el', 'Age / Sex', 'Edad / Sexo'),
('Spanish (Latin American)', 'el', 'Age / Sex:', 'Edad / Sexo:'),
('Spanish (Latin American)', 'el', 'All rights reserved.', 'Todos los derechos reservados.'),
('Spanish (Latin American)', 'el', 'Anatomical Region', 'Región Anatómica'),
('Spanish (Latin American)', 'el', 'Anatomical Region:', 'Región Anatómica:'),
('Spanish (Latin American)', 'el', 'Appointment Management', 'Gestión de Turnos'),
('Spanish (Latin American)', 'el', 'April', 'Abril'),
('Spanish (Latin American)', 'el', 'Are you sure you want to finalize the report and generate the PDF? Once finalized, the status will change to "Completed".', '¿Está seguro de que desea finalizar el informe y generar el PDF? Una vez finalizado, el estado cambiará a "Completado".'),
('Spanish (Latin American)', 'el', 'Attached Document', 'Documento Adjunto'),
('Spanish (Latin American)', 'el', 'August', 'Agosto'),
('Spanish (Latin American)', 'el', 'automatic', 'automática'),
('Spanish (Latin American)', 'el', 'Batch ID', 'ID de Lote'),
('Spanish (Latin American)', 'el', 'Biochemical Validation Recorded', 'Validación Bioquímica Registrada'),
('Spanish (Latin American)', 'el', 'BIOCHEMISTRY & DIAGNOSTIC SERVICE', 'SERVICIO DE BIOQUÍMICA Y DIAGNÓSTICO'),
('Spanish (Latin American)', 'el', 'Biochemistry and Clinical Diagnostics Service', 'Servicio de Bioquímica y Diagnóstico Clínico'),
('Spanish (Latin American)', 'el', 'Bone Densitometry (DEXA)', 'Densitometría Ósea (DEXA)'),
('Spanish (Latin American)', 'el', 'Cancel', 'Cancelar'),
('Spanish (Latin American)', 'el', 'Cancelled', 'Cancelado'),
('Spanish (Latin American)', 'el', 'Chart / PID:', 'Historia / PID:'),
('Spanish (Latin American)', 'el', 'Close', 'Cerrar'),
('Spanish (Latin American)', 'el', 'Committed to diagnostic excellence, medical innovation and confidentiality in the care of your health.', 'Comprometidos con la excelencia diagnóstica, innovación médica y la confidencialidad en el cuidado de su salud.'),
('Spanish (Latin American)', 'el', 'Communicate privately with your doctors and receive post-visit instructions.', 'Comunícate de manera privada con tus médicos y recibe indicaciones post-consulta.'),
('Spanish (Latin American)', 'el', 'COMPREHENSIVE CLINICAL LABORATORY REPORT', 'INFORME DE LABORATORIO CLÍNICO INTEGRAL'),
('Spanish (Latin American)', 'el', 'Comprehensive Digital Medical Record', 'Historia Clínica Digital Integral'),
('Spanish (Latin American)', 'el', 'Computed Tomography', 'Tomografía Computada'),
('Spanish (Latin American)', 'el', 'Computed Tomography (CT)', 'Tomografía Computada (TC)'),
('Spanish (Latin American)', 'el', 'Confidential Information', 'Información Confidencial'),
('Spanish (Latin American)', 'el', 'Connected', 'Conectado'),
('Spanish (Latin American)', 'el', 'Contains determinations outside the usual reference range', 'Contiene determinaciones fuera del rango de referencia habitual'),
('Spanish (Latin American)', 'el', 'CRITICAL', 'CRÍTICO'),
('Spanish (Latin American)', 'el', 'CT (Computed Tomography)', 'TC (Tomografía Computada)'),
('Spanish (Latin American)', 'el', 'Date', 'Fecha'),
('Spanish (Latin American)', 'el', 'Dear Patient', 'Estimado Paciente'),
('Spanish (Latin American)', 'el', 'December', 'Diciembre'),
('Spanish (Latin American)', 'el', 'Densitometry', 'Densitometría'),
('Spanish (Latin American)', 'el', 'Describe in detail the findings observed in the study...', 'Describa en detalle los hallazgos observados en el estudio...'),
('Spanish (Latin American)', 'el', 'Describe the protocol, sequences or projections used...', 'Describa el protocolo, las secuencias o las proyecciones utilizadas...'),
('Spanish (Latin American)', 'el', 'det.', 'det.'),
('Spanish (Latin American)', 'el', 'Determination / Analyte', 'Determinación / Analito'),
('Spanish (Latin American)', 'el', 'Determinations in progress or without numeric breakdown.', 'Determinaciones en proceso o sin desglose numérico.'),
('Spanish (Latin American)', 'el', 'DEXA (Bone Densitometry)', 'DEXA (Densitometría Ósea)'),
('Spanish (Latin American)', 'el', 'DEXA Normal', 'DEXA Normal'),
('Spanish (Latin American)', 'el', 'Diagnostic Imaging', 'Diagnóstico por Imágenes'),
('Spanish (Latin American)', 'el', 'Diagnostic Imaging & DICOM', 'Diagnóstico por Imágenes & DICOM'),
('Spanish (Latin American)', 'el', 'Diagnostic Imaging Report', 'Informe de Diagnóstico por Imágenes'),
('Spanish (Latin American)', 'el', 'Diagnostic Imaging Service', 'Servicio de Diagnóstico por Imágenes'),
('Spanish (Latin American)', 'el', 'Diagnostic Imaging Study', 'Estudio de Diagnóstico por Imágenes'),
('Spanish (Latin American)', 'el', 'Diagnostic Service', 'Servicio de Diagnóstico'),
('Spanish (Latin American)', 'el', 'DICOM Study Ready', 'Estudio DICOM Listo'),
('Spanish (Latin American)', 'el', 'Digitally Signed Document', 'Documento Firmado Digitalmente'),
('Spanish (Latin American)', 'el', 'DNI', 'DNI'),
('Spanish (Latin American)', 'el', 'Document Available', 'Documento Disponible'),
('Spanish (Latin American)', 'el', 'Document generated digitally on', 'Documento generado digitalmente el'),
('Spanish (Latin American)', 'el', 'Document recorded in the medical record', 'Documento Registrado en Historia Clínica'),
('Spanish (Latin American)', 'el', 'Document unavailable', 'Documento no disponible'),
('Spanish (Latin American)', 'el', 'Dompdf not found. Please verify composer install.', 'Dompdf no encontrado. Verifique composer install.'),
('Spanish (Latin American)', 'el', 'Download', 'Descargar'),
('Spanish (Latin American)', 'el', 'Download file', 'Descargar archivo'),
('Spanish (Latin American)', 'el', 'Download PDF', 'Descargar PDF'),
('Spanish (Latin American)', 'el', 'Download PDF report', 'Descargar informe PDF'),
('Spanish (Latin American)', 'el', 'E.g: your ID or username', 'Ej: tu DNI o usuario'),
('Spanish (Latin American)', 'el', 'ECG (Electrocardiogram)', 'ECG (Electrocardiograma)'),
('Spanish (Latin American)', 'el', 'Edit Report', 'Editar Informe'),
('Spanish (Latin American)', 'el', 'Email', 'Correo'),
('Spanish (Latin American)', 'el', 'Encounter', 'Encuentro'),
('Spanish (Latin American)', 'el', 'Encounter / Total Panels', 'Encuentro / Total de Paneles'),
('Spanish (Latin American)', 'el', 'encounters', 'encuentros'),
('Spanish (Latin American)', 'el', 'End-to-End Encryption (HIPAA / Law 25.326)', 'Cifrado de Extremo a Extremo (HIPAA / Ley 25.326)'),
('Spanish (Latin American)', 'el', 'Error generating OneTimeAuth token for SSO OpenEMR', 'Error generando token OneTimeAuth para SSO OpenEMR'),
('Spanish (Latin American)', 'el', 'Error saving document: ', 'Error al guardar el documento: '),
('Spanish (Latin American)', 'el', 'Error: Document not found or you do not have permission to view this file.', 'Error: Documento no encontrado o no tiene permisos para visualizar este archivo.'),
('Spanish (Latin American)', 'el', 'Error: Invalid document request.', 'Error: Solicitud de documento inválida.'),
('Spanish (Latin American)', 'el', 'Error: Report not found or you do not have permission to access the requested document.', 'Error: Informe no encontrado o no tiene permisos para acceder al documento solicitado.'),
('Spanish (Latin American)', 'el', 'Error: Unrecognized report type.', 'Error: Tipo de informe no reconocido.'),
('Spanish (Latin American)', 'el', 'Existing value not in list:', 'Valor existente no está en la lista:'),
('Spanish (Latin American)', 'el', 'February', 'Febrero'),
('Spanish (Latin American)', 'el', 'Female', 'Femenino'),
('Spanish (Latin American)', 'el', 'Final diagnostic synthesis of the study...', 'Síntesis diagnóstica final del estudio...'),
('Spanish (Latin American)', 'el', 'Findings', 'Hallazgos'),
('Spanish (Latin American)', 'el', 'Folder:', 'Carpeta:'),
('Spanish (Latin American)', 'el', 'Follow-up recommendations, clinical correlation, additional studies...', 'Recomendaciones de seguimiento, correlación clínica, estudios adicionales...'),
('Spanish (Latin American)', 'el', 'Full OpenEMR Portal', 'Portal Completo OpenEMR'),
('Spanish (Latin American)', 'el', 'Full OpenEMR Portal (Appointments and Messaging)', 'Portal Integral OpenEMR (Turnos y Mensajería)'),
('Spanish (Latin American)', 'el', 'Generating official document...', 'Generando documento oficial...'),
('Spanish (Latin American)', 'el', 'Go Directly to the OpenEMR Portal', 'Ingresar Directo a OpenEMR Portal'),
('Spanish (Latin American)', 'el', 'grouped studies', 'análisis agrupados'),
('Spanish (Latin American)', 'el', 'Health Center', 'Centro de Salud'),
('Spanish (Latin American)', 'el', 'Hello', 'Hola'),
('Spanish (Latin American)', 'el', 'HIGH (H)', 'ALTO (H)'),
('Spanish (Latin American)', 'el', 'History / PID', 'Historia / PID'),
('Spanish (Latin American)', 'el', 'ID / Document', 'ID / Documento'),
('Spanish (Latin American)', 'el', 'ID / Document:', 'ID / Documento:'),
('Spanish (Latin American)', 'el', 'If no folder is selected, the automatic category will be used according to the modality (e.g.: MRI  Magnetic Resonance).', 'Si no se selecciona carpeta, se usará la categoría automática según la modalidad (ej.: RMN → Resonancia Magnética).'),
('Spanish (Latin American)', 'el', 'image', 'imagen'),
('Spanish (Latin American)', 'el', 'IMAGE (JPG/PNG)', 'IMAGEN (JPG/PNG)'),
('Spanish (Latin American)', 'el', 'Image Available', 'Imagen Disponible'),
('Spanish (Latin American)', 'el', 'Image Viewer', 'Visor de Imagen'),
('Spanish (Latin American)', 'el', 'images', 'imágenes'),
('Spanish (Latin American)', 'el', 'Images on PACS Server', 'Imágenes en Servidor PACS'),
('Spanish (Latin American)', 'el', 'Imaging and Diagnostic Services', 'Servicios de Imágenes y Diagnóstico'),
('Spanish (Latin American)', 'el', 'IMAGING DIAGNOSTIC REPORT', 'INFORME DE DIAGNÓSTICO POR IMÁGENES'),
('Spanish (Latin American)', 'el', 'Imaging Report', 'Informe de Imágenes'),
('Spanish (Latin American)', 'el', 'Imaging Report — View', 'Informe de Imágenes — Vista'),
('Spanish (Latin American)', 'el', 'Imaging Studies', 'Estudios Imagen'),
('Spanish (Latin American)', 'el', 'imaging studies and documents', 'estudios de imágenes y documentos'),
('Spanish (Latin American)', 'el', 'Imaging Study', 'Estudio de Imagen'),
('Spanish (Latin American)', 'el', 'IMG (Diagnostic Imaging)', 'IMG (Diagnóstico por Imágenes)'),
('Spanish (Latin American)', 'el', 'In Progress / Pending', 'En proceso / Pendiente'),
('Spanish (Latin American)', 'el', 'Incorrect password. Please verify your credentials.', 'Contraseña incorrecta. Por favor, verifique sus credenciales.'),
('Spanish (Latin American)', 'el', 'Instantly access your laboratory results, diagnostic imaging studies and DICOM images.', 'Consulta al instante tus informes de laboratorio, diagnósticos por imágenes y estudios DICOM.'),
('Spanish (Latin American)', 'el', 'Institutional Clinical Form — OpenEMR', 'Formulario Clínico Institucional — OpenEMR'),
('Spanish (Latin American)', 'el', 'INSTITUTIONAL ELECTRONIC VALIDATION', 'VALIDACIÓN ELECTRÓNICA INSTITUCIONAL'),
('Spanish (Latin American)', 'el', 'Institutional Website', 'Sitio Web Institucional'),
('Spanish (Latin American)', 'el', 'Interpretation / Descriptive Findings', 'Interpretación / Hallazgos Descriptivos'),
('Spanish (Latin American)', 'el', 'Invalid credentials or patient not registered in the portal.', 'Credenciales inválidas o paciente no registrado en el portal.'),
('Spanish (Latin American)', 'el', 'Invalid response from Orthanc', 'Respuesta inválida de Orthanc'),
('Spanish (Latin American)', 'el', 'is recorded in the system but its physical path could not be read from local storage.', 'está registrado en el sistema pero su ruta física no pudo ser leída en el almacenamiento local.'),
('Spanish (Latin American)', 'el', 'Issue Date', 'Fecha de Emisión'),
('Spanish (Latin American)', 'el', 'Issue Date:', 'Fecha de Emisión:'),
('Spanish (Latin American)', 'el', 'Its validity and confidentiality are protected by current health regulations (Law 25.326 / HIPAA).', 'Su validez y confidencialidad están protegidas por las normas sanitarias vigentes (Ley 25.326 / HIPAA).'),
('Spanish (Latin American)', 'el', 'January', 'Enero'),
('Spanish (Latin American)', 'el', 'July', 'Julio'),
('Spanish (Latin American)', 'el', 'June', 'Junio'),
('Spanish (Latin American)', 'el', 'Lab Document', 'Documento de Laboratorio'),
('Spanish (Latin American)', 'el', 'Lab Encounters', 'Encuentros de Lab'),
('Spanish (Latin American)', 'el', 'Lab Panel', 'Panel de Laboratorio'),
('Spanish (Latin American)', 'el', 'Laboratory Protocol', 'Protocolo de Laboratorio'),
('Spanish (Latin American)', 'el', 'Laboratory Results', 'Resultados de Laboratorio'),
('Spanish (Latin American)', 'el', 'Log in automatically to the full OpenEMR Portal', 'Ingresar automáticamente al Portal Completo OpenEMR'),
('Spanish (Latin American)', 'el', 'Log Out', 'Cerrar Sesión'),
('Spanish (Latin American)', 'el', 'Log out securely', 'Cerrar sesión segura'),
('Spanish (Latin American)', 'el', 'Login successful.', 'Inicio de sesión exitoso.'),
('Spanish (Latin American)', 'el', 'LOW (L)', 'BAJO (L)'),
('Spanish (Latin American)', 'el', 'M.D. / M.P. Radiology', 'M.N. / M.P. Radiología'),
('Spanish (Latin American)', 'el', 'Magnetic Resonance Imaging', 'Resonancia Magnética'),
('Spanish (Latin American)', 'el', 'Magnetic Resonance Imaging (MRI)', 'Resonancia Magnética (RMN)'),
('Spanish (Latin American)', 'el', 'Male', 'Masculino'),
('Spanish (Latin American)', 'el', 'Mammography', 'Mamografía'),
('Spanish (Latin American)', 'el', 'Mammography (MG)', 'Mamografía (MG)'),
('Spanish (Latin American)', 'el', 'Mammography Normal', 'Mamografía Normal'),
('Spanish (Latin American)', 'el', 'March', 'Marzo'),
('Spanish (Latin American)', 'el', 'May', 'Mayo'),
('Spanish (Latin American)', 'el', 'Medical Record / PID', 'Historia Clínica / PID'),
('Spanish (Latin American)', 'el', 'Medicine / Diagnostic Imaging', 'Medicina / Diagnóstico por Imágenes'),
('Spanish (Latin American)', 'el', 'MG (Mammography)', 'MG (Mamografía)'),
('Spanish (Latin American)', 'el', 'Modality', 'Modalidad'),
('Spanish (Latin American)', 'el', 'Modality *', 'Modalidad *'),
('Spanish (Latin American)', 'el', 'Modality:', 'Modalidad:'),
('Spanish (Latin American)', 'el', 'MRI (Magnetic Resonance)', 'RMN (Resonancia Magnética)'),
('Spanish (Latin American)', 'el', 'MRI Normal', 'RMN Normal'),
('Spanish (Latin American)', 'el', 'My Studies and Results', 'Mis Estudios y Resultados'),
('Spanish (Latin American)', 'el', 'Need to schedule appointments or contact your doctor?', '¿Necesitas agendar turnos o contactar a tu médico?'),
('Spanish (Latin American)', 'el', 'No analyses found registered for this encounter.', 'No se encontraron análisis registrados para este encuentro.'),
('Spanish (Latin American)', 'el', 'No categories available.', 'No hay categorías disponibles.'),
('Spanish (Latin American)', 'el', 'No date', 'Sin fecha'),
('Spanish (Latin American)', 'el', 'No imaging studies recorded', 'No se registran estudios de imágenes'),
('Spanish (Latin American)', 'el', 'No laboratory results found', 'No se encontraron análisis de laboratorio'),
('Spanish (Latin American)', 'el', 'No morphological alterations or acute focal lesions observed in the explored region. Anatomical structures within normal limits for age and patient history.', 'No se observan alteraciones morfológicas ni lesiones focales agudas en la región explorada. Estructuras anatómicas dentro de límites normales para la edad y los antecedentes del paciente.'),
('Spanish (Latin American)', 'el', 'No report data.', 'No hay datos del informe.'),
('Spanish (Latin American)', 'el', 'Normal', 'Normal'),
('Spanish (Latin American)', 'el', 'Not registered', 'No registrado'),
('Spanish (Latin American)', 'el', 'Not specified', 'No especificado'),
('Spanish (Latin American)', 'el', 'November', 'Noviembre'),
('Spanish (Latin American)', 'el', 'Observations', 'Observaciones'),
('Spanish (Latin American)', 'el', 'October', 'Octubre'),
('Spanish (Latin American)', 'el', 'Official Approved Report', 'Informe Oficial Aprobado'),
('Spanish (Latin American)', 'el', 'OFFICIAL MEDICAL REPORT', 'INFORME MÉDICO OFICIAL'),
('Spanish (Latin American)', 'el', 'OHIF Viewer', 'Visor OHIF'),
('Spanish (Latin American)', 'el', 'Open in Tab', 'Abrir en Pestaña'),
('Spanish (Latin American)', 'el', 'Open PDF in a separate tab', 'Abrir PDF en pestaña independiente'),
('Spanish (Latin American)', 'el', 'Open the PDF report in a new tab', 'Abrir el informe PDF en una pestaña nueva'),
('Spanish (Latin American)', 'el', 'Open the radiology report in a new tab', 'Abrir el informe radiológico en una pestaña nueva'),
('Spanish (Latin American)', 'el', 'OpenEMR Portal', 'Portal OpenEMR'),
('Spanish (Latin American)', 'el', 'Order', 'Orden'),
('Spanish (Latin American)', 'el', 'Ordering physician', 'Médico solicitante'),
('Spanish (Latin American)', 'el', 'Orthanc PACS Study', 'Estudio PACS Orthanc'),
('Spanish (Latin American)', 'el', 'Other', 'Otro'),
('Spanish (Latin American)', 'el', 'Other / Not specified', 'Otro / No especificado'),
('Spanish (Latin American)', 'el', 'Other physician (type name)', 'Otro médico (escribir nombre)'),
('Spanish (Latin American)', 'el', 'Password', 'Contraseña'),
('Spanish (Latin American)', 'el', 'Patient', 'Paciente'),
('Spanish (Latin American)', 'el', 'Patient Express Portal', 'Portal Express del Paciente'),
('Spanish (Latin American)', 'el', 'Patient Express Portal v1.2', 'Patient Express Portal v1.2'),
('Spanish (Latin American)', 'el', 'Patient Login', 'Ingreso de Pacientes'),
('Spanish (Latin American)', 'el', 'Patient:', 'Paciente:'),
('Spanish (Latin American)', 'el', 'PDF DOCUMENT', 'DOCUMENTO PDF'),
('Spanish (Latin American)', 'el', 'PHOTO (Graphic Record)', 'FOTO (Registro Gráfico)'),
('Spanish (Latin American)', 'el', 'Physician:', 'Médico:'),
('Spanish (Latin American)', 'el', 'Please complete: Modality, Anatomical Region, Interpretation/Findings and Conclusion before finalizing the report.', 'Por favor, complete: Modalidad, Región Anatómica, Interpretación/Hallazgos y Conclusión antes de finalizar el informe.'),
('Spanish (Latin American)', 'el', 'Please enter your username/ID and password.', 'Ingrese su usuario/ID y contraseña.'),
('Spanish (Latin American)', 'el', 'Portal access is disabled for this patient. Please contact the medical center.', 'El acceso al portal está deshabilitado para este paciente. Por favor, contacte al centro médico.'),
('Spanish (Latin American)', 'el', 'Portal Username / ID / Email', 'Usuario del Portal / DNI / Email'),
('Spanish (Latin American)', 'el', 'Preliminary / In Progress', 'Preliminar / En Proceso'),
('Spanish (Latin American)', 'el', 'Prescriptions & Medication', 'Recetas & Medicación'),
('Spanish (Latin American)', 'el', 'Primary Care Physician', 'Médico de Cabecera'),
('Spanish (Latin American)', 'el', 'Protocol', 'Protocolo'),
('Spanish (Latin American)', 'el', 'Quick access to clinical test results, diagnostic imaging reports and the DICOM viewer.', 'Acceso rápido a resultados de análisis clínicos, informes de diagnóstico por imágenes y visor DICOM.'),
('Spanish (Latin American)', 'el', 'Ready to access the Full Portal?', '¿Listo para ingresar al Portal Integral?'),
('Spanish (Latin American)', 'el', 'Ref', 'Ref'),
('Spanish (Latin American)', 'el', 'Reference Values', 'Valores de Referencia'),
('Spanish (Latin American)', 'el', 'Region / Anatomical Area *', 'Región / Área Anatómica *'),
('Spanish (Latin American)', 'el', 'Registered path', 'Ruta registrada'),
('Spanish (Latin American)', 'el', 'Registered:', 'Registrado:'),
('Spanish (Latin American)', 'el', 'Report Available', 'Informe Disponible'),
('Spanish (Latin American)', 'el', 'Report Date', 'Fecha del Informe'),
('Spanish (Latin American)', 'el', 'Report ID:', 'ID del Informe:'),
('Spanish (Latin American)', 'el', 'Report No.:', 'Informe N.º:'),
('Spanish (Latin American)', 'el', 'Report not found or no access.', 'Informe no encontrado o sin acceso.'),
('Spanish (Latin American)', 'el', 'Report Preview', 'Vista Previa de Informe'),
('Spanish (Latin American)', 'el', 'Reporting Physician', 'Médico Informante'),
('Spanish (Latin American)', 'el', 'Reporting Physician:', 'Médico Informante:'),
('Spanish (Latin American)', 'el', 'Request, reschedule and check your upcoming appointments with specialists and scheduled studies.', 'Solicita, reprograma y consulta tus próximas citas con especialistas y estudios programados.'),
('Spanish (Latin American)', 'el', 'Requested by', 'Solicitado por'),
('Spanish (Latin American)', 'el', 'Requester(s)', 'Solicitante(s)'),
('Spanish (Latin American)', 'el', 'Requesting Physician', 'Médico Solicitante'),
('Spanish (Latin American)', 'el', 'Requesting physician name', 'Nombre del médico solicitante'),
('Spanish (Latin American)', 'el', 'Requesting Physician:', 'Médico Solicitante:'),
('Spanish (Latin American)', 'el', 'Requesting Physician(s)', 'Médico(s) Solicitante(s)'),
('Spanish (Latin American)', 'el', 'Requesting Service', 'Servicio Solicitante'),
('Spanish (Latin American)', 'el', 'Result', 'Resultado'),
('Spanish (Latin American)', 'el', 'Result Date', 'Fecha Resultados'),
('Spanish (Latin American)', 'el', 'Results Date', 'Fecha de Resultados'),
('Spanish (Latin American)', 'el', 'Review your medical prescription history, doses and instructions for ongoing treatments.', 'Revisa tu historial de prescripciones médicas, dosis e indicaciones de tratamientos continuos.'),
('Spanish (Latin American)', 'el', 'Rx Normal', 'Rx Normal'),
('Spanish (Latin American)', 'el', 'Save and Generate PDF', 'Guardar y Generar PDF'),
('Spanish (Latin American)', 'el', 'Save Draft', 'Guardar Borrador'),
('Spanish (Latin American)', 'el', 'Scan to view the study in the DICOM viewer (OHIF)', 'Escanee para ver el estudio en el visor DICOM (OHIF)'),
('Spanish (Latin American)', 'el', 'Search by encounter, date, test or doctor...', 'Buscar por encuentro, fecha, análisis o médico...'),
('Spanish (Latin American)', 'el', 'Search study, modality or file...', 'Buscar estudio, modalidad o archivo...'),
('Spanish (Latin American)', 'el', 'Secure Messaging', 'Mensajería Segura'),
('Spanish (Latin American)', 'el', 'Secure SSL Connection', 'Conexión Segura SSL'),
('Spanish (Latin American)', 'el', 'Select the folder where the PDF will be saved in the patient chart (Patient Documents)', 'Seleccione la carpeta donde se guardará el PDF en el legajo del paciente (Documentos del Paciente)'),
('Spanish (Latin American)', 'el', 'September', 'Septiembre'),
('Spanish (Latin American)', 'el', 'Service / Requester', 'Servicio / Solicitante'),
('Spanish (Latin American)', 'el', 'Service Physicians', 'Médicos del Servicio'),
('Spanish (Latin American)', 'el', 'Service:', 'Servicio:'),
('Spanish (Latin American)', 'el', 'Sex', 'Sexo'),
('Spanish (Latin American)', 'el', 'Showing', 'Mostrando'),
('Spanish (Latin American)', 'el', 'Specialist Physician', 'Médico Especialista'),
('Spanish (Latin American)', 'el', 'Specimen', 'Muestra'),
('Spanish (Latin American)', 'el', 'Status', 'Estado'),
('Spanish (Latin American)', 'el', 'studies', 'estudios'),
('Spanish (Latin American)', 'el', 'studies in total', 'estudios en total'),
('Spanish (Latin American)', 'el', 'Studies included in this encounter:', 'Estudios incluidos en este encuentro:'),
('Spanish (Latin American)', 'el', 'study', 'análisis'),
('Spanish (Latin American)', 'el', 'Study Date', 'Fecha del Estudio'),
('Spanish (Latin American)', 'el', 'Study Date:', 'Fecha del Estudio:'),
('Spanish (Latin American)', 'el', 'Study performed according to standard protocol. Correlate with clinical data.', 'Estudio realizado según protocolo estándar. Correlacionar con datos clínicos.'),
('Spanish (Latin American)', 'el', 'Study UID', 'UID del Estudio'),
('Spanish (Latin American)', 'el', 'Study UID:', 'UID del Estudio:'),
('Spanish (Latin American)', 'el', 'Synchronized in Orthanc PACS', 'Sincronizado en PACS Orthanc'),
('Spanish (Latin American)', 'el', 'TC Normal', 'TC Normal'),
('Spanish (Latin American)', 'el', 'Technique and Descriptive Findings', 'Técnica y Hallazgos Descriptivos'),
('Spanish (Latin American)', 'el', 'Technique / Methodology (Sequences)', 'Técnica / Metodología (Secuencias)'),
('Spanish (Latin American)', 'el', 'Tel', 'Tel.'),
('Spanish (Latin American)', 'el', 'The Dompdf\Dompdf class is not available.', 'La clase Dompdf\Dompdf no está disponible.'),
('Spanish (Latin American)', 'el', 'The Express Portal lets you access your reports and viewers very quickly. If you need to interact with your healthcare team, request appointments or download additional clinical documentation, use the centralized portal.', 'El Portal Express te permite acceder de forma ultrarrápida a tus informes y visores. Si necesitas interactuar con tu equipo de salud, solicitar turnos o descargar documentación clínica complementaria, utiliza el portal centralizado.'),
('Spanish (Latin American)', 'el', 'The file', 'El archivo'),
('Spanish (Latin American)', 'el', 'The OpenEMR platform will open in a new secure tab.', 'Se abrirá la plataforma OpenEMR en una nueva pestaña segura.'),
('Spanish (Latin American)', 'el', 'The results and studies available on this portal are for consultation by the patient and their treating physician. The final interpretation must be made exclusively by a healthcare professional.', 'Los resultados y estudios disponibles en este portal son para consulta del paciente y su médico tratante. La interpretación definitiva debe ser realizada exclusivamente por un profesional de la salud.'),
('Spanish (Latin American)', 'el', 'This document is an official medical protocol issued by', 'Este documento es un protocolo médico oficial emitido por'),
('Spanish (Latin American)', 'el', 'This document is an official medical report issued by', 'Este documento es un informe médico oficial emitido por'),
('Spanish (Latin American)', 'el', 'Ultrasound', 'Ecografía'),
('Spanish (Latin American)', 'el', 'Ultrasound (US)', 'Ecografía (US)'),
('Spanish (Latin American)', 'el', 'Unified Electronic Imaging Protocol', 'Protocolo Electrónico Unificado de Imágenes'),
('Spanish (Latin American)', 'el', 'Unified Electronic Protocol', 'Protocolo Electrónico Unificado'),
('Spanish (Latin American)', 'el', 'Units', 'Unidades'),
('Spanish (Latin American)', 'el', 'US (Ultrasound)', 'US (Ecografía)'),
('Spanish (Latin American)', 'el', 'US Normal', 'US Normal'),
('Spanish (Latin American)', 'el', 'Useful Links', 'Enlaces de Interés'),
('Spanish (Latin American)', 'el', 'values to interpret', 'valores a interpretar'),
('Spanish (Latin American)', 'el', 'Verify authenticity at', 'Verifique la autenticidad en'),
('Spanish (Latin American)', 'el', 'View / Download PDF', 'Ver / Bajar PDF'),
('Spanish (Latin American)', 'el', 'View DICOM Image (OHIF)', 'Ver Imagen DICOM (OHIF)'),
('Spanish (Latin American)', 'el', 'View Document', 'Ver Documento'),
('Spanish (Latin American)', 'el', 'View Full PDF Report', 'Ver Informe PDF Completo'),
('Spanish (Latin American)', 'el', 'View Image', 'Ver Imagen'),
('Spanish (Latin American)', 'el', 'View in advanced radiology viewer OHIF', 'Visualizar en Visor Radiológico Avanzado OHIF'),
('Spanish (Latin American)', 'el', 'View PDF', 'Ver PDF'),
('Spanish (Latin American)', 'el', 'View PDF Document', 'Ver Documento PDF'),
('Spanish (Latin American)', 'el', 'View Report', 'Ver Informe'),
('Spanish (Latin American)', 'el', 'View Report (PDF)', 'Ver Informe (PDF)'),
('Spanish (Latin American)', 'el', 'Warning: C_Document::retrieve_action failed', 'Aviso: C_Document::retrieve_action falló'),
('Spanish (Latin American)', 'el', 'Warning: Could not query Orthanc PACS', 'Aviso: No se pudo consultar Orthanc PACS'),
('Spanish (Latin American)', 'el', 'Web', 'Web'),
('Spanish (Latin American)', 'el', 'Welcome to your medical consultation center. Here you can review your studies and diagnostic protocols instantly.', 'Bienvenido a tu centro de consulta médica. Aquí puedes revisar tus estudios y protocolos de diagnóstico al instante.'),
('Spanish (Latin American)', 'el', 'X-Ray', 'Rayos X'),
('Spanish (Latin American)', 'el', 'X-Ray — Digital Radiography', 'Rayos X — Radiografía Digital'),
('Spanish (Latin American)', 'el', 'X-Ray (Digital Radiography)', 'Rayos X (Radiografía Digital)'),
('Spanish (Latin American)', 'el', 'XR (Digital Radiography)', 'RX (Radiografía Digital)'),
('Spanish (Latin American)', 'el', 'You do not have clinical test reports registered under valid procedures yet. When the laboratory processes and validates your samples, they will appear grouped by encounter in this section.', 'Aún no tienes informes de análisis clínicos registrados bajo procedimientos válidos. Cuando el laboratorio procese y valide tus muestras, aparecerán agrupados por encuentro en esta sección.'),
('Spanish (Latin American)', 'el', 'You do not have radiology, CT, MRI, ultrasound or imaging studies uploaded to the system yet.', 'Aún no tienes estudios de radiología, tomografía, resonancia, ecografía o imágenes cargadas en el sistema.'),
('Spanish (Latin American)', 'el', 'You have securely logged out.', 'Has cerrado tu sesión de forma segura.'),
('Spanish (Latin American)', 'el', 'You must log in to access the portal.', 'Debe iniciar sesión para acceder al portal.'),
('Spanish (Latin American)', 'el', '✔ Completed', '✔ Completado'),
('Spanish (Latin American)', 'el', '⏳ Draft', '⏳ Borrador'),
('Spanish (Latin American)', 'el', '📋 Study Data', '📋 Datos del Estudio'),
('Spanish (Latin American)', 'el', '🔬 Technique / Methodology', '🔬 Técnica / Metodología'),
('Spanish (Latin American)', 'el', '🩻 Interpretation / Findings', '🩻 Interpretación / Hallazgos'),
('Spanish (Latin American)', 'el', '📌 Conclusion / Diagnostic Impression', '📌 Conclusión / Impresión Diagnóstica'),
('Spanish (Latin American)', 'el', '💬 Observations and Suggestions', '💬 Observaciones y Sugerencias'),
('Spanish (Latin American)', 'el', '📂 PDF Destination Folder', '📂 Carpeta Destino del PDF'),
('Spanish (Latin American)', 'el', '— No folder selected (automatic will be used) —', '— Sin carpeta seleccionada (se usará la automática) —'),
('Spanish (Latin American)', 'el', 'If no folder is selected, the automatic category will be used according to the modality (e.g.: MRI → Magnetic Resonance).', 'Si no se selecciona carpeta, se usará la categoría automática según la modalidad (ej.: RMN → Resonancia Magnética).'),
('Spanish (Latin American)', 'el', 'Conclusion', 'Conclusión'),
('Spanish (Latin American)', 'el', ' years', ' años'),
('Spanish (Latin American)', 'el', 'DIAGNOSTIC IMAGING REPORT', 'INFORME DE DIAGNÓSTICO POR IMÁGENES'),
('Spanish (Latin American)', 'el', 'ENCOUNTER', 'ENCUENTRO'),
('Spanish (Latin American)', 'el', 'DATE', 'FECHA'),
('Spanish (Latin American)', 'el', 'Also upload to the PACS server', 'Además sube al servidor PACS'),
('Spanish (Latin American)', 'el', 'When enabled, uploaded files are copied to the PACS server in addition to the patient documents folder.', 'Cuando está activada, los archivos subidos también se copian al servidor PACS además de a la carpeta de documentos del paciente.'),
('Spanish (Latin American)', 'el', 'No PACS', 'Sin PACS'),
('Spanish (Latin American)', 'el', 'PACS upload was not enabled.', 'La subida al PACS no está activada.'),
('Spanish (Latin American)', 'el', 'Document saved. PACS upload was not enabled.', 'Documento guardado. La subida al PACS no está activada.'),
('Spanish (Latin American)', 'el', 'ZIP processed: ', 'ZIP procesado: '),
('Spanish (Latin American)', 'el', ' document(s) saved individually.', ' documento(s) guardados individualmente.'),
('Spanish (Latin American)', 'el', 'PACS zip upload failed: ', 'Fallo en la subida del ZIP al PACS: '),
('Spanish (Latin American)', 'el', 'Standard projections were obtained according to the requested region using a direct digital radiography (DDR) system. Dose optimized according to the ALARA protocol.', 'Se realizaron proyecciones estándar según la región solicitada con equipo de radiografía digital directa (DDR). Dosis optimizada según protocolo ALARA.'),
('Spanish (Latin American)', 'el', 'FINDINGS:\n- Normal bone density and architecture.\n- Joint spaces of normal width.\n- Soft tissues without signs of alteration.\n- No evidence of lytic lesions, pathological sclerosis or fractures.\n- Preserved skeletal alignment.\n- No abnormal calcifications in the plane of the image.', 'HALLAZGOS:\n- Trama ósea de densidad y arquitectura conservadas.\n- Espacios articulares de amplitud normal.\n- Partes blandas sin signos de alteración.\n- Sin evidencia de lesiones líticas, esclerosis patológica ni fracturas.\n- Alineación esquelética conservada.\n- Sin calcificaciones anómalas en el plano de la imagen.'),
('Spanish (Latin American)', 'el', 'Radiological study within normal limits for the patient''s age and sex. No significant pathological findings are observed.', 'Estudio radiológico dentro de límites normales para la edad y sexo del paciente. No se observan hallazgos patológicos significativos.'),
('Spanish (Latin American)', 'el', 'Clinical correlation is suggested. If symptoms persist, consider additional workup studies.', 'Se sugiere correlación clínica. Ante persistencia de síntomas, considerar estudios complementarios.'),
('Spanish (Latin American)', 'el', 'Multi-slice computed tomography (MSCT) with helical acquisition. Axial slices 1-2 mm thick with multiplanar reformats (MPR) in coronal and sagittal planes. Technique without/with intravenous iodinated contrast administration according to clinical indication.', 'Tomografía computada multicorte (TCMC) con adquisición helicoidal. Cortes axiales de 1-2mm de grosor con reformateos multiplanares (MPR) en planos coronal y sagital. Técnica sin/con administración de contraste yodado endovenoso según indicación clínica.'),
('Spanish (Latin American)', 'el', 'FINDINGS:\n- Normal bone density and morphology.\n- Adjacent soft tissues without significant alterations.\n- No evidence of collections, hematomas or space-occupying lesions.\n- Well-defined fat planes without infiltration.\n- Vessels of normal caliber and density (in contrast-enhanced studies).\n- Regional lymph nodes of normal size and morphology.', 'HALLAZGOS:\n- Estructuras óseas de densidad y morfología normales.\n- Partes blandas adyacentes sin alteraciones significativas.\n- Sin evidencia de colecciones, hematomas ni lesiones ocupantes de espacio.\n- Espacios grasos bien definidos, sin infiltración.\n- Vasculatura de calibre y densidad normales (en estudios contrastados).\n- Ganglios linfáticos regionales de tamaño y morfología dentro de parámetros normales.'),
('Spanish (Latin American)', 'el', 'Computed tomography without significant pathological findings. Evaluated structures within normal limits.', 'Tomografía computada sin hallazgos patológicos significativos. Estructuras estudiadas dentro de límites normales.'),
('Spanish (Latin American)', 'el', 'Clinical correlation recommended. No contraindications for conventional follow-up.', 'Correlación clínica recomendada. Sin contraindicaciones para seguimiento convencional.'),
('Spanish (Latin American)', 'el', 'Magnetic resonance imaging with a 1.5 Tesla (or 3T) unit. Sequences obtained: axial T1 SE, axial/coronal/sagittal T2 TSE, coronal STIR, DWI with ADC maps (when indicated). Without/With intravenous gadolinium administration (0.1 mmol/kg) according to protocol.', 'Resonancia magnética con unidad de 1.5 Tesla (o 3T). Secuencias obtenidas: T1 SE axial, T2 TSE axial/coronal/sagital, STIR coronal, DWI con mapas ADC (cuando indicado). Sin/Con administración de gadolinio endovenoso (0.1 mmol/kg) según protocolo.'),
('Spanish (Latin American)', 'el', 'FINDINGS:\n- Homogeneous signal and intensity of the structures, within normal parameters on all evaluated sequences.\n- No evidence of lesions with restricted diffusion.\n- Preserved tissue interfaces.\n- No mass effect or displacement of structures.\n- Preserved subchondral bone signal.\n- No collections or areas of pathological post-contrast enhancement (if administered).', 'HALLAZGOS:\n- Estructuras de señal e intensidad homogéneas, dentro de parámetros normales en todas las secuencias evaluadas.\n- Sin evidencia de lesiones con restricción a la difusión.\n- Interfaces tisulares conservadas.\n- Sin efecto de masa ni desplazamiento de estructuras.\n- Señal del hueso subcondral conservada.\n- Sin colecciones ni áreas de realce patológico post-contraste (si se administró).'),
('Spanish (Latin American)', 'el', 'Magnetic resonance imaging within normal limits. No significant alterations on the evaluated sequences.', 'Resonancia magnética dentro de límites normales. Sin alteraciones significativas en las secuencias evaluadas.'),
('Spanish (Latin American)', 'el', 'Correlation with clinical findings and prior studies is recommended. Follow-up at the treating physician''s discretion.', 'Se recomienda correlación con clínica y estudios previos. Control evolutivo a criterio del médico tratante.'),
('Spanish (Latin American)', 'el', 'Ultrasound performed with a multifrequency linear/convex transducer (7.5-12 MHz / 3.5-5 MHz depending on the region). Real-time technique with color and spectral Doppler when indicated.', 'Ecografía realizada con transductor multifrecuencia lineal/convex (7.5–12MHz / 3.5–5MHz según región). Técnica en tiempo real con Doppler color y espectral cuando indicado.'),
('Spanish (Latin American)', 'el', 'FINDINGS:\n- Explored organs/structures of normal size, echogenicity and morphology.\n- No evidence of cystic, solid or mixed lesions.\n- Preserved vascularization on color Doppler.\n- No dilatation of ductal structures.\n- No free fluid in the cavity.\n- Regional lymph nodes without morphological alterations.', 'HALLAZGOS:\n- Órganos/estructuras exploradas de tamaño, ecogenicidad y morfología normales.\n- Sin evidencia de imágenes quísticas, sólidas ni mixtas.\n- Vascularización conservada al Doppler color.\n- Sin dilatación de estructuras ductuales.\n- Sin líquido libre en cavidad.\n- Ganglios regionales sin alteraciones morfológicas.'),
('Spanish (Latin American)', 'el', 'Ultrasound study without pathological findings. Explored structures within normal limits for age and sex.', 'Estudio ecográfico sin hallazgos patológicos. Estructuras exploradas dentro de parámetros normales para la edad y sexo.'),
('Spanish (Latin American)', 'el', 'Clinical-analytical correlation is suggested. Follow-up at the treating physician''s discretion.', 'Se sugiere correlación clínico-analítica. Seguimiento a criterio del médico tratante.'),
('Spanish (Latin American)', 'el', 'Bilateral digital mammography with craniocaudal (CC) and mediolateral oblique (MLO) projections bilaterally. Tomosynthesis added according to institutional protocol.', 'Mamografía digital bilateral con proyecciones craneocaudal (CC) y oblicua mediolateral (OML) bilateral. Tomosíntesis añadida según protocolo institucional.'),
('Spanish (Latin American)', 'el', 'FINDINGS:\nACR Breast composition: Type A - predominantly fatty breasts (or as applicable).\n\n- No density asymmetry between both breasts.\n- No suspicious microcalcifications (no clustering, morphology or pathological distribution).\n- No distortion of the glandular architecture.\n- No nodules, masses or asymmetric densities.\n- Normal-appearing skin and nipple.\n- No suspicious axillary lymphadenopathy.', 'HALLAZGOS:\nACR Composición mamaria: Tipo A — Mamas predominantemente grasas (o según corresponda).\n\n- Sin asimetría de densidad entre ambas mamas.\n- Sin microcalcificaciones sospechosas (sin agrupamiento, morfología ni distribución patológica).\n- Sin distorsión de la arquitectura glandular.\n- Sin nódulos, masas ni densidades asimétricas.\n- Piel y pezón de aspecto normal.\n- Sin adenopatías axilares sospechosas.'),
('Spanish (Latin American)', 'el', 'BI-RADS 1: Negative. Mammographic study without pathological findings. Routine annual follow-up recommended.', 'BI-RADS 1: Negativo. Estudio mamográfico sin hallazgos patológicos. Se recomienda control anual de rutina.'),
('Spanish (Latin American)', 'el', 'Routine mammographic follow-up according to screening protocol. Correlation with clinical examination.', 'Seguimiento mamográfico de rutina según protocolo de cribado. Correlación con exploración clínica.'),
('Spanish (Latin American)', 'el', 'Bone densitometry by dual-energy X-ray absorptiometry (DEXA). Regions evaluated: lumbar spine (L1-L4) and proximal hip (femoral neck and total). Equipment calibrated according to ISCD standards.', 'Densitometría ósea por absorciometría de rayos X de doble energía (DEXA). Regiones evaluadas: columna lumbar (L1-L4) y cadera proximal (cuello femoral y total). Equipo calibrado según estándares ISCD.'),
('Spanish (Latin American)', 'el', 'RESULTS:\n\nLUMBAR SPINE (L1-L4):\n- Bone mineral density (BMD): ___ g/cm²\n- T-Score: ___  /  Z-Score: ___\n\nFEMORAL NECK:\n- Bone mineral density (BMD): ___ g/cm²\n- T-Score: ___  /  Z-Score: ___\n\nTOTAL HIP:\n- Bone mineral density (BMD): ___ g/cm²\n- T-Score: ___  /  Z-Score: ___\n\nValues within the expected range for the age group. No evidence of osteopenia or osteoporosis.', 'RESULTADOS:\n\nCOLUMNA LUMBAR (L1–L4):\n- Densidad mineral ósea (DMO): ___ g/cm²\n- T-Score: ___  /  Z-Score: ___\n\nCUELLO FEMORAL:\n- Densidad mineral ósea (DMO): ___ g/cm²\n- T-Score: ___  /  Z-Score: ___\n\nTOTAL CADERA:\n- Densidad mineral ósea (DMO): ___ g/cm²\n- T-Score: ___  /  Z-Score: ___\n\nValores dentro de rango esperado para el grupo etario. Sin evidencia de osteopenia ni osteoporosis.'),
('Spanish (Latin American)', 'el', 'Bone mineral density within normal parameters according to WHO criteria. T-Score ≥ -1.0 SD at all evaluated regions.', 'Densidad mineral ósea dentro de parámetros normales según criterios OMS. T-Score ≥ -1.0 DS en todas las regiones evaluadas.'),
('Spanish (Latin American)', 'el', 'Healthy habits recommended: diet rich in calcium and vitamin D, regular physical activity. Follow-up in 2 years according to clinical indication.', 'Se recomienda mantener hábitos saludables: dieta rica en calcio y vitamina D, actividad física regular. Control en 2 años según indicación clínica.');

-- ============================================================================
-- SYNC: Populate lang_languages, lang_constants and lang_definitions
-- Idempotent: safe to re-run, preserves existing entries.
--
-- IMPORTANT: lang_constants.constant_name uses utf8mb4_bin (case-sensitive),
-- while lang_custom.constant_name uses utf8mb3_general_ci.
-- That is why we use CONVERT(lc.constant_name USING utf8mb4) in the JOINs
-- so MySQL compares using the utf8mb4_bin collation of lang_constants.
-- ============================================================================

-- 2. Create language if it does not exist
INSERT INTO lang_languages (lang_code, lang_description)
SELECT DISTINCT lc.lang_code, lc.lang_description
FROM lang_custom lc
WHERE NOT EXISTS (
    SELECT 1 FROM lang_languages l WHERE l.lang_code = lc.lang_code
);

-- 3. Create new constants (case-sensitive comparison)
INSERT INTO lang_constants (constant_name)
SELECT DISTINCT lc.constant_name
FROM lang_custom lc
WHERE lc.constant_name <> ''
  AND NOT EXISTS (
    SELECT 1 FROM lang_constants c
    WHERE c.constant_name = CONVERT(lc.constant_name USING utf8mb4)
  );

-- 4. Insert new definitions
INSERT INTO lang_definitions (cons_id, lang_id, definition)
SELECT c.cons_id, l.lang_id, lc.definition
FROM lang_custom lc
INNER JOIN lang_constants c
    ON c.constant_name = CONVERT(lc.constant_name USING utf8mb4)
INNER JOIN lang_languages l
    ON l.lang_code = lc.lang_code
WHERE NOT EXISTS (
    SELECT 1 FROM lang_definitions d
    WHERE d.cons_id = c.cons_id AND d.lang_id = l.lang_id
);

-- 5. Update modified translations
UPDATE lang_definitions d
INNER JOIN lang_constants c ON c.cons_id = d.cons_id
INNER JOIN lang_languages l ON l.lang_id = d.lang_id
INNER JOIN lang_custom lc
    ON l.lang_code = lc.lang_code
    AND c.constant_name = CONVERT(lc.constant_name USING utf8mb4)
SET d.definition = lc.definition
WHERE IFNULL(d.definition, '') <> IFNULL(lc.definition, '');

COMMIT;
